### ISSUE TITLE
error cuando no se ingresa la edad

### ISSUE THREAD

**Issue by jmbigi** [camila2626/proyecto-productos2#2]
Otra cosa, en modificar, cuando modifico edad, si pongo enter, da error: <<2>>Nueva edad(Ingresa 0 para no modificar): 
Traceback (most recent call last):
  File "/home/ubuntu/Descargas/proyecto-productos.py", line 115, in <module>
    modificarEmpleado(empleados)
  File "/home/ubuntu/Descargas/proyecto-productos.py", line 54, in modificarEmpleado
    edad = int(input(f"<<{empleado['edad']}>>Nueva edad(Ingresa 0 para no modificar): "))
ValueError: invalid literal for int() with base 10: ''

**Comment by camila2626** [comment]
es de otro proyecto
